ci:
  skip:
  - just-all
repos:
- repo: https://github.com/nim65s/pre-commit-sort
  rev: v0.1.0
  hooks:
  - id: pre-commit-sort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: just-all
    name: just-all
    entry: just all
    language: rust
    pass_filenames: false
